// <auto-generated />
namespace BugTracker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class ChatFirstmigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChatFirstmigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202005081112095_Chat. First migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
