// <auto-generated />
namespace BugTracker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class HoooraaayIrealizedthepoint : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HoooraaayIrealizedthepoint));
        
        string IMigrationMetadata.Id
        {
            get { return "202005051951571_Hoooraaay! I realized the point!"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
