// <auto-generated />
namespace BugTracker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class HoooraaayIrealizedthepoint2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HoooraaayIrealizedthepoint2));
        
        string IMigrationMetadata.Id
        {
            get { return "202005052030189_Hoooraaay! I realized the point! 2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
